#coding:utf-8 
'''
Date&Time: 01.06.11 10:28
@author: kir
'''
from m3.ui.ext.containers.forms import ExtPanel
from m3.ui.ext.windows.window import ExtWindow

class queryBuilderWindow(ExtWindow):
    
    def __init__(self, *args, **kwargs):
        super(queryBuilderWindow, self).__init__(*args, **kwargs)
        self.initialize()

    def initialize(self):
        '''AUTOGENERATED'''
        self.layout = 'fit'
        self.title = 'queryBuilderWindow'
        self.maximizable = True
        self.minimizable = True
        self.items.extend([self.crate_main_window()])

    def crate_main_window(self, container_class=ExtPanel):
        cont = container_class()
        '''AUTOGENERATED'''
        cont.layout = 'fit'

        return cont