#coding: utf-8

from m3.ui.ext.all_components import *

class TestOne(ExtWindow):
    '''©
    Простой класс'''

    def __init__(self, *args, **kwargs):
        '''©
        Конструктор класса
        '''
        super(TestOne, self).__init__(*args, **kwargs)
        self.initialize()

    def initialize(self):
        '''©
        AUTOGENERATIONS! Не редактировать!!
        DO No Touch
        '''
        self.layout = 'fit'
        self.name = 'Ext window'
        self.title = 'Trololo'
        base_panel = ExtPanel()
        base_panel.layout = 'absolute'
        base_panel.name = 'Ext panel'
        base_panel.title = 'Im panel '
        simple_form = ExtForm()
        simple_form.layout = 'form'
        simple_form.name = 'Ext form'
        simple_form.title = 'Im form '
        inner_panel = ExtPanel()
        inner_panel.width = 100
        inner_panel.layout = 'absolute 2'
        inner_panel.name = 'Ext panel'
        inner_panel.title = 'Im panel 2'
        
        f = ExtStringField()
        f.anchor = '100%'        
        inner_panel._items.append(f)
        
        self._items.append(base_panel)
        self._items.append(simple_form)
        simple_form._items.append(inner_panel)

    def ata(self):
        pass
    
    
class Claz(ExtWindow):

    def __init__(self, *args, **kwargs):
        super(Claz, self).__init__(*args, **kwargs)
        self.initialize()

    def initialize(self):
        '''AUTOGENERATED'''
        self.title = u'Окно'
        
        panel_1 = ExtPanel()
        panel_1.layout = 'fit'
        panel_1.title = 'New panel'
        panel_1.header = False
        
        grid_panel_1 = ExtGrid()
        grid_panel_1.title = 'New grid'
        grid_panel_1.header = False
        
        array_store_1 = ExtDataStore()
        array_store_1.store_id = 'New store'
        array_store_1.id_index = '0'
        
        gridColumn_1 = ExtGridColumn()
        gridColumn_1.header = 'column'
        gridColumn_1.data_index = 'Foo'
        gridColumn_1.menu_disabled = True
        
        gridColumn_2 = ExtGridColumn()
        gridColumn_2.header = 'column'
        gridColumn_2.data_index = 'Foo'
        gridColumn_2.menu_disabled = True
        
        grid_panel_1.store = array_store_1
        
        grid_panel_1.columns.extend([gridColumn_1, gridColumn_2])
        panel_1._items.extend([grid_panel_1])
        self._items.extend([panel_1])
        
        self.panel_1 = panel_1
        self.grid_panel_1 = grid_panel_1
        self.array_store_1 = array_store_1
        self.gridColumn_1 = gridColumn_1
        self.gridColumn_2 = gridColumn_2
        
def ata(a, b):
    panel_2.store = store_1