#coding: utf-8

from m3.ui.ext.all_components import *

class TestOne(ExtWindow):
    '''©
    Простой класс'''

    def __init__(self, *args, **kwargs):
        '''©
        Конструктор класса
        '''
        super(TestOne, self).__init__(*args, **kwargs)
        self.initialize()

    def initialize(self):
        '''©
        AUTOGENERATIONS! Не редактировать!!
        DO No Touch
        '''
        self.layout = 'fit'
        self.name = 'Ext window'
        self.title = 'Trololo'
        base_panel = ExtPanel()
        base_panel.layout = 'absolute'
        base_panel.name = 'Ext panel'
        base_panel.title = 'Im panel '
        simple_form = ExtForm()
        simple_form.layout = 'form'
        simple_form.name = 'Ext form'
        simple_form.title = 'Im form '
        inner_panel = ExtPanel()
        inner_panel.width = 100
        inner_panel.layout = 'absolute 2'
        inner_panel.name = 'Ext panel'
        inner_panel.title = 'Im panel 2'
        
        f = ExtStringField()
        f.anchor = '100%'        
        inner_panel._items.append(f)
        
        self._items.append(base_panel)
        self._items.append(simple_form)
        simple_form._items.append(inner_panel)

    def ata(self):
        pass
    
    
class Claz(ExtWindow):

    def __init__(self, *args, **kwargs):
        super(Claz, self).__init__(*args, **kwargs)
        self.initialize()

    def initialize(self):
        '''AUTOGENERATED'''
        self.layout = 'fit'
        self.title = '123'
        self.name = 'name_123'
        
        tab_panel_1 = ExtTabPanel()
        tab_panel_1.title = 'New panel'
        tab_panel_1.active_tab = '0'
        tab_panel_1.header = False
        
        panel_1 = ExtPanel()
        panel_1.layout = 'form'
        panel_1.title = 'New panel'
        panel_1.padding = '5'
        panel_1.header = False
        
        text_area_1 = ExtTextArea()
        text_area_1.label = '1123321'
        text_area_1.anchor = '50%'
        
        date_field_1 = ExtDateField()
        date_field_1.label = '423'
        
        panel_2 = ExtPanel()
        panel_2.header = False
        panel_2.layout = 'auto'
        panel_2.title = 'New panel'
        
        grid_1 = ExtGrid()
        
        
        store_1 = ExtDataStore()
        
        grid_1.store = store_1
        
        panel_1._items.extend([text_area_1, date_field_1])
        tab_panel_1._items.extend([panel_1, panel_2, grid_1])
        self._items.extend([tab_panel_1])
        
        self.tab_panel_1 = tab_panel_1
        self.panel_1 = panel_1
        self.text_area_1 = text_area_1
        self.date_field_1 = date_field_1
        self.panel_2 = panel_2
        
def ata(a, b):
    panel_2.store = store_1