#coding: utf-8

from m3.ui.ext.all_components import *

class TestOne(ExtWindow):
    '''©
    Простой класс'''

    def __init__(self, *args, **kwargs):
        '''©
        Конструктор класса
        '''
        super(TestOne, self).__init__(*args, **kwargs)
        self.initialize()

    def initialize(self):
        '''©
        AUTOGENERATIONS! Не редактировать!!
        DO No Touch
        '''
        self.layout = 'fit'
        self.name = 'Ext window'
        self.title = 'Trololo'
        base_panel = ExtPanel()
        base_panel.layout = 'absolute'
        base_panel.name = 'Ext panel'
        base_panel.title = 'Im panel '
        simple_form = ExtForm()
        simple_form.layout = 'form'
        simple_form.name = 'Ext form'
        simple_form.title = 'Im form '
        inner_panel = ExtPanel()
        inner_panel.width = 100
        inner_panel.layout = 'absolute 2'
        inner_panel.name = 'Ext panel'
        inner_panel.title = 'Im panel 2'
        
        f = ExtStringField()
        f.anchor = '100%'        
        inner_panel._items.append(f)
        
        self._items.append(base_panel)
        self._items.append(simple_form)
        simple_form._items.append(inner_panel)

    def ata(self):
        pass
    
    
class Claz(ExtWindow):

    def __init__(self, *args, **kwargs):
        super(Claz, self).__init__(*args, **kwargs)
        self.initialize()

    def initialize(self):
        '''AUTOGENERATED'''
        self.title = u'Окно'
        self.layout = 'auto'
        
def ata(a, b):
    if a:
        data = 1
    elif b:
        data = 2
    else:
        data = 3
 